// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Para desenvolvimento local/Lovable, use as URLs diretas:
// const SUPABASE_URL = "https://setjuoelbyidxnwyrsqm.supabase.co";
// const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNldGp1b2VsYnlpZHhud3lyc3FtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2NzY4MzIsImV4cCI6MjA2ODI1MjgzMn0.w-HibV8Ma1Rwb2Cg25MB93oO5ZPsdciZwcrP6N1nPsE";

// Para ambientes externos/produção, use as variáveis de ambiente:
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
